name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - run: npm install
    - run: npm run gulp
    - name: push
      continue-on-error: true
      if: ${{ !env.ACT }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add dist/
        git commit -m "Deploy distribition files"
        git push
    - name: Semantic Release
      id: tag
      uses: hennejg/github-tag-action@v4.3.1
      with:
        github_token : ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ""
    - name: release if new tags
      uses: softprops/action-gh-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.tag.outputs.new_tag }}
      with:
        tag_name: ${{ steps.tag.outputs.new_tag }}
        name: ${{ steps.tag.outputs.new_tag }}
        body: ${{ steps.tag.outputs.changelog }}
        files: |
          dist/*


