name: Sync Files
on: 
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - "src/**"
      - "assets/**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Sync files
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          SKIP_PR: true
          COMMIT_PREFIX: "[SYNC]"
          COMMIT_BODY: "Updated from assets"
          ORIGINAL_MESSAGE: true

